# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'Myo Hero' do

use_frameworks!
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'

end